#!/bin/bash
#
# chkconfig: 2345 90 90 
# description: Regroup, via shotgun.
# processname: shotgun

NAME=shotgun-regroup
REGROUPDIR=/var/www/regroup
PIDFILE=/var/run/$NAME.pid
LOGFILE=/var/log/$NAME.log
SHOTGUN=/usr/local/bin/shotgun
RUBY=/usr/local/bin/ruby
RUNCMD="$RUBY regroup.rb -p 9393"

# just for a moment.
SAVEDPATH=$PATH
export PATH=/usr/local/bin:$PATH

start () {
    if [ -f $PIDFILE ]; then
        printf "But it's already running?\n"
    else
        printf "%-50s" "Reaching for shotgun..."
        cd $REGROUPDIR
        PID=`$RUNCMD >> $LOGFILE 2>&1 & echo $!`
        if [ -z "$PID" ]; then
            # I'm really sorry for the ridiculously informative message.
            printf "(nah)\n"
        else
            echo $PID > $PIDFILE
            printf "(got it)\n"
        fi
    fi
}

stop() {
    if [ -f $PIDFILE ]; then
        printf "%-50s" "Putting an end to Regroup..."
        PID=`cat $PIDFILE`
        kill -3 $PID
        rm $PIDFILE
        printf "(done)\n"
    else
        printf "I'm not judging you, but it doesn't seem to be running.\n"
    fi
}

case "$1" in
start)
    start
;;
stop)
    stop
;;
status)
    if [ -f $PIDFILE ]; then
        printf "It seems to be running, yeah.\n"
    else
        printf "Doesn't seem to be running.\n"
    fi
;;
restart)
    stop
    start 
;;
*)
    printf "Usage: $0 {status|start|stop|restart}"
    exit 1
esac

# clean up.
export PATH=$SAVEDPATH
